# Generated by Django 4.2.7 on 2023-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('used', models.BooleanField(default=True)),
                ('price', models.CharField(max_length=20)),
                ('register', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('image_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
