# Generated by Django 4.2.7 on 2023-11-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image_url',
            field=models.ImageField(null=True, upload_to='books_img'),
        ),
    ]
