# Generated by Django 4.2.7 on 2023-11-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='image_url',
            new_name='image',
        ),
    ]
