# Generated by Django 4.2.7 on 2023-11-24 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_image_url_books_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
