# Generated by Django 4.2.7 on 2023-12-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='account',
            name='town_city',
        ),
    ]
